language: python

python:
    - "2.7"
    - "3.4"

install:
    - pip install coverage coveralls --use-mirrors

script: coverage run --branch --source=editorconfig_tools setup.py test

after_success: coveralls
